version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: shoppingapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        - ConnectionStrings__ShoppingApp=Host=db;Database=shoppingapp;Username=admin;Password=password
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
        - "5039:5039"
    depends_on:
        - db
volumes:
  db-data: